import Link from "next/link";
import { ArrowUpRight, Check, Radio, Sparkles, Zap } from "lucide-react";
import { Brand } from "@/components/brand";

export default function Home() {
  return <main className="min-h-screen overflow-hidden">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><Brand /><div className="flex items-center gap-3"><Link href="/login" className="hidden px-4 py-2 text-sm font-bold sm:block">Sign in</Link><Link href="/login" className="rounded-full bg-[#171713] px-5 py-3 text-sm font-bold text-white">Create your profile</Link></div></nav>
    <section className="grid-bg relative border-y border-black/10">
      <div className="mx-auto grid min-h-[720px] max-w-7xl items-center gap-14 px-6 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-10">
        <div className="relative z-10"><div className="pill mb-7 inline-flex items-center gap-2 bg-white/70 px-4 py-2 text-xs font-bold uppercase tracking-[.16em]"><Radio size={14} className="text-[#ff5a36]"/> NFC-powered identity</div><h1 className="display max-w-3xl text-6xl font-extrabold leading-[.94] sm:text-7xl lg:text-[92px]">One tap.<br/><span className="text-[#ff5a36]">Your whole story.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-black/65 sm:text-xl">Turn your Namtek smart tag into a living digital profile. Share who you are, what you do, and where people can find you.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/login" className="flex items-center gap-2 rounded-full bg-[#ff5a36] px-6 py-4 font-bold text-white">Build my profile <ArrowUpRight size={18}/></Link><Link href="/p/alex" className="pill bg-white px-6 py-4 font-bold">View live demo</Link></div><div className="mt-8 flex gap-6 text-sm text-black/55"><span className="flex items-center gap-2"><Check size={16}/> No app needed</span><span className="flex items-center gap-2"><Check size={16}/> Update anytime</span></div></div>
        <div className="relative mx-auto w-full max-w-[430px]"><div className="absolute -left-16 top-12 h-32 w-32 rounded-full bg-[#d8ff62] blur-sm"/><div className="absolute -right-12 bottom-20 h-44 w-44 rounded-full bg-[#ffb9a9] blur-sm"/><div className="card-shadow relative rotate-[2deg] rounded-[38px] border border-black/10 bg-[#171713] p-3"><div className="rounded-[29px] bg-white p-7"><div className="mb-16 flex items-center justify-between"><span className="rounded-full bg-[#f1eee5] px-3 py-1.5 text-xs font-bold">namtek / alex</span><Sparkles size={18}/></div><div className="mb-5 flex h-20 w-20 items-center justify-center rounded-full bg-[#ff5a36] text-2xl font-extrabold text-white">AM</div><h2 className="display text-3xl font-extrabold">Alex Morgan</h2><p className="mt-1 text-black/55">Product designer · Detroit</p><p className="mt-5 leading-7 text-black/70">I design simple, human products and help ambitious teams turn good ideas into useful experiences.</p><div className="mt-7 space-y-3">{["My portfolio","Connect on LinkedIn","Book a conversation"].map((x,i)=><div key={x} className={`flex items-center justify-between rounded-2xl px-5 py-4 font-bold ${i===0?"bg-[#d8ff62]":"bg-[#f1eee5]"}`}>{x}<ArrowUpRight size={17}/></div>)}</div></div></div></div>
      </div>
    </section>
    <section className="bg-[#171713] px-6 py-24 text-white lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#d8ff62]">Made to stay current</p><div className="mt-5 grid gap-10 lg:grid-cols-2"><h2 className="display text-5xl font-extrabold leading-tight sm:text-6xl">Your tag stays the same.<br/>Your profile keeps moving.</h2><div className="grid gap-4 sm:grid-cols-2">{[[Zap,"Instant sharing","A tap opens your profile in any browser."],[Sparkles,"Always yours","Change links, details, and colors anytime."]].map(([Icon,title,text])=>{const I=Icon as typeof Zap;return <div key={title as string} className="rounded-3xl border border-white/15 p-6"><I className="mb-8 text-[#ff5a36]"/><h3 className="text-xl font-bold">{title as string}</h3><p className="mt-2 text-white/55">{text as string}</p></div>})}</div></div></div></section>
  </main>;
}
