create extension if not exists pgcrypto;

alter table public.tags
  add column if not exists flight_date date;

create table if not exists public.tag_trips (
  id uuid primary key default gen_random_uuid(),
  tag_id uuid not null references public.tags(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  airline text not null,
  flight_number text not null,
  flight_date date not null,
  origin text not null,
  destination text not null,
  status text not null default 'submitted' check (status in (
    'submitted', 'scheduled', 'delayed', 'in_flight', 'landed',
    'collected', 'lost', 'archived_unconfirmed'
  )),
  provider_flight_id text,
  provider_status text,
  scheduled_departure timestamptz,
  actual_departure timestamptz,
  scheduled_arrival timestamptz,
  actual_arrival timestamptz,
  next_reminder_at timestamptz,
  reminder_count integer not null default 0,
  completed_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists one_open_trip_per_tag
  on public.tag_trips(tag_id)
  where status not in ('collected', 'archived_unconfirmed');

create index if not exists tag_trips_sync_idx
  on public.tag_trips(status, flight_date);

create table if not exists public.trip_events (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.tag_trips(id) on delete cascade,
  event_type text not null,
  title text not null,
  detail text,
  source text not null default 'customer' check (source in ('customer', 'flight_provider', 'automation', 'finder')),
  event_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists trip_events_timeline_idx
  on public.trip_events(trip_id, event_at desc);

create table if not exists public.trip_notifications (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.tag_trips(id) on delete cascade,
  reminder_number integer not null,
  channel text not null check (channel in ('email', 'sms')),
  status text not null check (status in ('sent', 'skipped', 'failed')),
  detail text,
  created_at timestamptz not null default now(),
  unique (trip_id, reminder_number, channel)
);

alter table public.tag_trips enable row level security;
alter table public.trip_events enable row level security;
alter table public.trip_notifications enable row level security;

drop policy if exists "Owners manage their trips" on public.tag_trips;
create policy "Owners manage their trips" on public.tag_trips
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "Owners read their trip events" on public.trip_events;
create policy "Owners read their trip events" on public.trip_events
  for select using (
    exists (select 1 from public.tag_trips where tag_trips.id = trip_events.trip_id and tag_trips.owner_id = auth.uid())
  );

drop policy if exists "Owners add trip events" on public.trip_events;
create policy "Owners add trip events" on public.trip_events
  for insert with check (
    exists (select 1 from public.tag_trips where tag_trips.id = trip_events.trip_id and tag_trips.owner_id = auth.uid())
  );

drop policy if exists "Owners read trip notifications" on public.trip_notifications;
create policy "Owners read trip notifications" on public.trip_notifications
  for select using (
    exists (select 1 from public.tag_trips where tag_trips.id = trip_notifications.trip_id and tag_trips.owner_id = auth.uid())
  );
